### ISSUE TITLE
Release / Deploy Process Changes?

### ISSUE THREAD

**Issue by jah2488** [jah2488/classroom#113]
I was thinking it may be good going forward to make some changes to how/when we do deploys to _(hopefully)_ cut down on bugs and to increase reliability/consistency.

1. All deploys to heroku will be from a new `release` branch, no more deploying directly from master.
1. All deploys (except for hot fixes) will occur on the same day.
1. All deploys will be accompanied by a changelog update of some sort.
1. A new staging server will be setup on heroku for deploys from master.
1. Someone needs to verify everything is working on staging before creating a new release.

Thoughts, suggestions, criticisms?

**Comment by kurtisnelson** [comment]
We've now got an auto-deploying staging so all we need to worry about is hand testing staging before we promote to prod.

**Comment by jah2488** [comment]
@kurtisnelson Yah that covers most all of these.
