### ISSUE TITLE
deadline extensions and other edits on created assignments

### ISSUE THREAD

**Issue by magentanova** [jah2488/classroom#121]
A deadline has been extended on an assignment, but I don't believe I'm able to edit the deadline. It would be great to be able to edit the name and description as well, or to remove an assignment that I've changed my mind about.

Many of my issues are along the lines of "I would like this to be editable." I admit that there are many things in the app which are uneditable that I would like to see editable. Can we make some ... Editable Arrangements??

**Comment by jah2488** [comment]
Everything is supposed to be correct the first time. We believe in immutable instruction. 😛

In all seriousness, this is long overdue and sadly actually exists? 

If you are on the staff page for a particular assignment and you append `/edit` to the end of the URL it will open the edit page for that assignment. You can then change the name, body, or due date.

**Comment by magentanova** [comment]
I believe in demonstrating human frailty for my students by doing everything wrong the first time :/.

**Comment by kurtisnelson** [comment]
assignment edit actually works right now.
