### ISSUE TITLE
Campus create generates a blank page

### ISSUE THREAD

**Issue by dummied** [jah2488/classroom#125]
Trying to create a campus for Indianapolis using the following values using a newly created account authenticated via Google oAuth and a theironyard.com account:

Indianapolis
39.768189299999996
-86.1491837
Eastern timezone

Resulting page is empty (no HTML at all).

Going to try to replicate locally now.

**Comment by kurtisnelson** [comment]
you probably aren't marked as an instructor yet, let me do that for you.

**Comment by dummied** [comment]
Perfect. Meantime, are there any conditions wherein we could do that on sign up? I'm not really wanting to keep a yaml file or anything of instructor email addresses, but as part of the new instructor onboarding process, some interface to smooth adoption might not be a bad idea.

**Comment by kurtisnelson** [comment]
What manually has to be done right now is `Instructor.create(user: user)`. We could make it so that when you oauth with a TIY account it asks if you are an instructor or not.

**Comment by dummied** [comment]
:+1:

**Comment by kurtisnelson** [comment]
Closing this and opening a new issue.

**Comment by kurtisnelson** [comment]
Fixed!
https://tiy-classroom.herokuapp.com/staff/campuses
