### ISSUE TITLE
New Materialize acting a little off?

### ISSUE THREAD

**Issue by jah2488** [jah2488/classroom#154]
I quickly ran through the materialize PR and probably should have spent more time reviewing the dashboards. My students seem unable to click on some links on their end and on the instructor dash it looks a bit like this. Is it supposed to?

<img width="730" alt="screen shot 2015-10-12 at 10 01 48 am" src="https://cloud.githubusercontent.com/assets/249209/10431070/9644659a-70c8-11e5-933e-80f7b79f3438.png">

I'll try to spend some time this week cleaning this up, but it may take a few days.

**Comment by kurtisnelson** [comment]
The material icons are breaking, that's what all the hanging text is.
