### ISSUE TITLE
Submission feedback textarea too small

### ISSUE THREAD

**Issue by NicerHugs** [jah2488/classroom#164]
Only a few characters, which makes writing lengthy feedback very challenging. Also, please add overflow scroll to it even if you don't make it bigger!

**Comment by jah2488** [comment]
Good point. Will do.

**Comment by kurtisnelson** [comment]
dupe of #158

**Comment by kurtisnelson** [comment]
working this one

**Comment by kurtisnelson** [comment]
Fixed by #167

**Comment by NicerHugs** [comment]
@kurtisnelson doing feedback this am and text area is still tiny w no overflow: scroll

<img width="718" alt="screen shot 2015-10-19 at 9 09 19 am" src="https://cloud.githubusercontent.com/assets/8377050/10580033/1e58c372-7641-11e5-8007-ae81a1067a00.png">
