### ISSUE TITLE
Checkin and New Day Dates need to use Cohort Time Zone

### ISSUE THREAD

**Issue by jah2488** [jah2488/classroom#28]
Currently, creating a new day and creating a checkin for that day due not use the proper time zone and need to be adjusted.

**Comment by jah2488** [comment]
https://robots.thoughtbot.com/its-about-time-zones reference

**Comment by kurtisnelson** [comment]
I think this might be finally fixed.

**Comment by kurtisnelson** [comment]
yay! react re-write fixed this.
