### ISSUE TITLE
App sometimes hangs and then timeouts

### ISSUE THREAD

**Issue by jah2488** [jah2488/classroom#29]
The app is suffering from sporadic time outs that cause the whole dyno to need to be reset. My suspicion is that Refile is causing this issue with its self hosted sinatra based asset server. Possible fixes for that are to migrate from Refile over to Paperclip/Carrierwave + S3 or to up the dynos on heroku and hope that fixes the issue. 

Currently images are only being used for badges. So a third option could be to rip out the image upload functionality entirely and to just place all the badges into the assets folder and serve them directly from there.

(User profile images are generated via gravatar emails)

**Comment by kurtisnelson** [comment]
Seems to be fixed.

**Comment by jah2488** [comment]
I've had no problems since adding CDN and S3
