### ISSUE TITLE
New Day is Broken

### ISSUE THREAD

**Issue by kurtisnelson** [jah2488/classroom#3]
Creating a day right now seems to be broken, the `start` probably ends up in totally the wrong timezone. We should set the timezone based on the campus.

**Comment by jah2488** [comment]
The day creation is now working in production, but I did not go so far as to verify if the time zone is being set correctly.

**Comment by kurtisnelson** [comment]
Time zone seems to be defaulting to UTC. I guess we should assume the user means the timezone of the campus?
