### ISSUE TITLE
Something is wrong with how Days/Absences are now being calculated. 

### ISSUE THREAD

**Issue by jah2488** [jah2488/classroom#47]
My brand new cohort is on its 'first day'. _(I had to create a new day to see the dash as a student, apparently we don't allow students in before the first day currently. Thats fine.)_

![screen shot 2015-08-03 at 12 08 10 pm](https://cloud.githubusercontent.com/assets/249209/9043093/a8cb7702-39d8-11e5-9a81-787a0357c41e.png)

It says we are on **Day 2** for some reason and it also says this student has **1** absence when the first day hasn't ended yet?

**Comment by kurtisnelson** [comment]
I'll look at this.

**Comment by kurtisnelson** [comment]
Found the bug, the `create_first_day` callback never saves.
