### ISSUE TITLE
Improve Test Coverage

### ISSUE THREAD

**Issue by jah2488** [jah2488/classroom#8]
Now that more than a single person is using the application and now that other people are interested in developing in the app, its time to get serious about tests.

First step is to improve the test coverage of our current features to prevent regressions going forwards.

We can also start adding tests to any new features that we add. I imagine this will be a long running improvement as there are a lot of tests to write.

I got rspec/travis/codeclimate up and running and currently we do have some passing specs.

**Comment by jah2488** [comment]
![screen shot 2015-08-03 at 4 04 13 pm](https://cloud.githubusercontent.com/assets/249209/9047740/71bf587a-39f9-11e5-9f91-47706d918633.png)

**Comment by kurtisnelson** [comment]
CodeClimate disagrees at the moment.

**Comment by jah2488** [comment]
@kurtisnelson I love how their test coverage system works, as we add more tests, our overall coverage goes down, because now they see how much code is not tested, lol.

**Comment by jah2488** [comment]
![screen shot 2015-08-17 at 10 59 25 am](https://cloud.githubusercontent.com/assets/249209/9309412/17195ce6-44cf-11e5-9913-53f4c9f63cae.png)
Finally getting some accurate test coverage results from code climate.
