### ISSUE TITLE
CREATE DAY leads to white page

### ISSUE THREAD

**Issue by magentanova** [jah2488/classroom#87]
After I add a day, set a start time, and click the CREATE DAY button, I'm routed to a white page of death and no page is added.

**Comment by jah2488** [comment]
It seems the white page occurs when you try to create a second day for the same calendar day. This error should be handled and stated instead of just presenting a white screen :(

**Comment by magentanova** [comment]
it's not clear that in my case that's the issue. the only day that currently exists for my cohort is sunday aug 23. that is not today, and i cannot create a new day.

**Comment by jah2488** [comment]
@magentanova Ah, okay. It could be something else, that was what had happened the last time I ran into that bug.

**Comment by kurtisnelson** [comment]
Confirmed white screen happens when you create a day twice.
