### ISSUE TITLE
Assigning Badges

### ISSUE THREAD

**Issue by magentanova** [jah2488/classroom#89]
There seems to be no way to assign a badge.

**Comment by jah2488** [comment]
How so?

Currently you assign badges when grading a submission. You click the badges you want to award them then mark the assignment as completed. (This workflow for instructors should probably be documented someplace)

**Comment by magentanova** [comment]
Ah, okay. I had assumed they could be assigned freely. That works. I was just testing the feature out with a goofy badge and found no way to assign it.
