### ISSUE TITLE
Editing absences/tardies

### ISSUE THREAD

**Issue by magentanova** [jah2488/classroom#90]
I realize that this is what the adjustments feature is for, but it seems like it would be much more convenient (and probably very often needed as students get adjusted to the process) for the instructor to be able to just edit these things on the spot.

**Comment by kurtisnelson** [comment]
:+1: , I forget to start a day often and would like to just be able to fix it myself.

**Comment by jah2488** [comment]
The point of the checkin feature is to give the students a system that does not depend on the instructors fixing things for them. They are not children and we shouldn't need to be constantly updating and fixing tardies for them. If they don't want to have a tardy or absence on their record, they file for an adjustment. If I make a mistake, then I can adjust it.

That being said, it does make sense for their to be some way for instructors to simple override a value without needing to directly use the system.

**Comment by magentanova** [comment]
Indeed they are technically not children, but I expect that young adults overwhelmed with data on the first few days might forget that they need to visit this app and check in, and that I, overwhelmed with starting my first cohort, might forget to remind them.

I think the checkin feature is still immensely useful as a way to automate the tracking of attendance, and I'm not sure that the ability to override errors would interfere with that usefulness.

**Comment by jah2488** [comment]
I don't think having an override issue would interfere, I was just explaining why it wasn't added into the app up to this point.

:+1: 

You do have a point. I didn't have my students using this app until week 2 last cohort, but there is something to be said about setting expectations from the beginning.

**Comment by kurtisnelson** [comment]
Can we resolve this via the ability for an instructor to login as one of their students?
